version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: elev8_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'elev8_core'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./database_migrations:/docker-entrypoint-initdb.d

volumes:
  db_data:
